export const initialState = {
    user: null,
    orderList: null,
    // filterTerm: "all",
    allProducts: null,
    cart: null,
    // languageFilter: null,
    // allUsers: null,
    // allSongs: null,
    // allAlbums: null,
    // albumFilter: null,
    // song: 0,
    // isSongPlaying: false,
    // miniPlayer: false,
  };